### ISSUE TITLE
Without lidar

### ISSUE THREAD

**Issue by zazgf** [brade31919/radar_depth#10]
Hi, @brade31919 In the paper, it is mentioned that `Two-Stage architecture` can be used to filter radar instead of lidar, but in the program **def filter_radar_points(self, input_data):** are all applied lidar data to filter radar data. Can we generate preprocessed data without using lidar data?
My english is not very good, sorry.

**Comment by zazgf** [comment]
With reading the program, I learned a lot, Thank you very much for releasing the code.

**Comment by brade31919** [comment]
Hi @zazgf ,

The part you mentioned is actually in the data loader and that part was used to generate different sparse patterns for the experiments in Table 2 from our [paper](https://arxiv.org/pdf/2010.00058.pdf). So you can generate (1) normal radar measurements, (2) radar points filtered by the ground truth LiDAR scans, or (3) radar points filtered by the trained classifyer, etc. In the main experiment, we use (1), so there should be no concern related to "using lidar data to do the filtering".

**Comment by zazgf** [comment]
@brade31919 Thanks for your reply.
Does this mean that I can achieve the project function without lidar?
Thanks again.

**Comment by brade31919** [comment]
Hi @zazgf,

It depends on the sparsifier argument passed to the dataset construction (the name itself is a bit confusing). So if the sparsifier is "radar", then the inputs contain the concatenation of images and raw radar depth maps. If it's "radar_filtered", then the inputs are composed by images and filtered radar depth maps instead.

Therefore, as you can see in README.md, the sparsifier is set to "radar".

**Comment by zazgf** [comment]
@brade31919 Get your point, I didn't realize this before.I need pay more attention on code reading. Thanks.
