### ISSUE TITLE
Evaluation error  args = checkpoint['args'] 

### ISSUE THREAD

**Issue by zazgf** [brade31919/radar_depth#11]
@brade31919 ,
I debugged the code , and encountered the error in `main.py line 199` "args = checkpoint['args']",  error notice is `KeyError: 'args'`   I found checkpoint have function value 'arch'.
Can you help me sovle this problem?

**Comment by zazgf** [comment]
Hi, @brade31919 ,
I think just use `arch` instead of `args`, but I'm not sure
```python
args.arch = checkpoint['arch']
print(args)
```

**Comment by zazgf** [comment]
@brade31919 ,
Yes, when I edit the code `line 199` as above and ran out the desired result.
```bash
python main.py --evaluate /home/username/radar_depth/pretrained/resnet18_multistage.pth.tar --data nuscenes --arch resnet18_multistage_uncertainty_fixs --modality rgbd --sparsifier radar --decoder upproj
```
* set `num_workers=0` ,as My computer configuration is relatively low.

Thanks again for @brade31919's help.

**Comment by Kirstihly** [comment]
With the provided checkpoints, the keys are

`dict_keys(['arch', 'model_state_dict', 'optimizer_state_dict'])`

But if trained ourselves, the checkpoint will include

`dict_keys(['args', 'epoch', 'arch', 'model_state_dict', 'best_result', 'optimizer_state_dict'])`

**Comment by Abdulaaty** [comment]
Have you managed to get similar results to the publication when only evaluating the pretrained models? I got very bad results here (RMSE is in magnitude of 20 )

> @brade31919 , Yes, when I edit the code `line 199` as above and ran out the desired result.
> 
> ```shell
> python main.py --evaluate /home/username/radar_depth/pretrained/resnet18_multistage.pth.tar --data nuscenes --arch resnet18_multistage_uncertainty_fixs --modality rgbd --sparsifier radar --decoder upproj
> ```
> 
> * set `num_workers=0` ,as My computer configuration is relatively low.
> 
> Thanks again for @brade31919's help.

**Comment by zazgf** [comment]
@Abdulaaty Sorry for late reply. This is result what I got. 
![Screenshot from 2022-03-30 14-09-45](https://user-images.githubusercontent.com/49219511/160763298-a1846b63-2e21-4caf-b0f5-7571521e67cd.png)
And I did not commented code else.

**Comment by Abdulaaty** [comment]
@zazgf Thanks for your reply. I mean did you evaluate the pretrained models on the dataset that they provide in the repo (as in to replicate the results) and got the same results as they state in the paper?

**Comment by zazgf** [comment]
> @zazgf Thanks for your reply. I mean did you evaluate the pretrained models on the dataset that they provide in the repo (as in to replicate the results) and got the same results as they state in the paper?

I did not evaluate the models.
