### ISSUE TITLE
How to obtain ground truth depth image?

### ISSUE THREAD

**Issue by XXXVincent** [brade31919/radar_depth#3]
How to obtain ground truth depth image? By using Lidar 2 Camera projection and interpolate the projected points?

**Comment by brade31919** [comment]
Hi @XXXVincent ,

You can use the 3D transformation in the dataset to transform the 3D LiDAR points to the sensor coordinate of the camera sensor, and then you can use the camera intrinsics to project the points to 2D depth images.

Best,
Juan-Ting Lin

**Comment by isht7** [comment]
@brade31919 Thank you for the earlier reply. Does this mean that the ground truth images are quite sparse?

**Comment by brade31919** [comment]
Hi @isht7 
Yes, this is the situation for outdoor self-driving datasets. Currently, people rely on LiDAR sensor to collect the ground truths. Same for Kitti or Waymo datasets
