### ISSUE TITLE
Bidirectional radar sweeps

### ISSUE THREAD

**Issue by pjckoch** [brade31919/radar_depth#7]
Hi,

thanks again for sharing your work!

I have one more question regarding the radar sweeps:
I saw that you used radar sweeps t-1, t, t+1 for training. Did you also use radar sweeps from the future (t+1) to test your model as described in your paper or did you only use radar sweeps t-1, t for testing?

Thanks and best regards,
Patrick

**Comment by brade31919** [comment]
Hi @pjckoch 

Yes, we accumulated radar points from neighboring time steps (t, t-1, t+1), and you might have concern about "taking the measurements from the future". In this project, we were not dealing with a streaming task. At least, the inference time and latency were not our main concern. Therefore, by including radar points from t+1, you can simply treat it as making a delayed inference (prediction) at t+1, and here the latency is roughly equal to 1/13s according to the capture frequency of [their sensors](https://www.nuscenes.org/nuscenes#data-collection).

Why don't we use t, t-1, t-2? According to my understanding ([explained in this issue](https://github.com/brade31919/radar_depth/issues/6)), the radar sensors are not synced to the LiDAR and camera anyway, the radar measurements you used from the dataset can also come from the future (they also grabbed the measurement with the closest timestamp). Therefore, it's just a bit more convenient to grab measurements from 3 nearest time steps to minimize the alignment issue but increase the point counts.

Sincerely,
Juan-Ting Lin

**Comment by pjckoch** [comment]
Hi @brade31919 ,

ok, I see your point. Either way, I think it's a good idea to do this during training, since the radar data is already quite challenging to work with and introducing more misalignment makes it even less reliable. If inference time was a concern, one could then simply switch to using 2 or 3 past sweeps for testing. But I see that timing was not your focus. Just wanted to be sure which setting you used for evaluation.

As always, thanks a lot for your prompt and detailed reply.

Best regards,
Patrick
