### ISSUE TITLE
Own dataset make method

### ISSUE THREAD

**Issue by zazgf** [brade31919/radar_depth#9]
Hi @brade31919,
I am a rookie, forgive me for asking such a stupid question.
Can you give me a tutorial to train my data and apply the model to my own sensor? Or how do you deal with the image and radar data？
Thank you in advance.

**Comment by brade31919** [comment]
Hi @zazgf ,

It actually depends on the data you have, the sensor setup, and the dataset structure. For example, if you have radar data (3D point format) and an image, you have to get the 3D transformation from radar sensor coordinate to camera sensor coordinate. Then, you can transform the 3D points. With the camera intrinsics, you can do the projection onto image plane.

Then you have to preprocess the projected radar depth map and the image into similar format as the ones I used. After finishing all these steps, you can use the model to predict the depth maps for you.

Note that the model I provided was trained on nuscenes dataset (an outdoor dataset), so there might be some domain gaps.

**Comment by zazgf** [comment]
@brade31919 
I have read your project code, and under your suggestion and explanation, I know what to do next.
Wish you have a happy day.
